### ISSUE TITLE
How to use the Imgur API?

### ISSUE THREAD

**Issue by madscientista** [EthanArbuckle/Apollo-CustomApiCredentials#11]
I see that the code updated with Imgur support but how do I actually use it? I am registering an application in Imgur and it asked for callback. So what would I put? There’s also rapid api key that would require so much money to register 👀. Further advise needed. 

thanks!

**Comment by Barusu-rem** [comment]
> I see that the code updated with Imgur support but how do I actually use it? I am registering an application in Imgur and it asked for callback. So what would I put? There’s also rapid api key that would require so much money to register 👀. Further advise needed.
> 
> thanks!

Spoiler I couldn't get it to work but this is what I tried.
1. Sign up for X-rapid api key and copy key
<img width="1373" alt="SCR-20230630-thzf" src="https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/124480833/28d774ad-083b-4dc5-b664-94cd11bd3c45">
2. Create an imgur account and creat an app with the following parameters

[https://api.imgur.com/oauth2/addclient](https://api.imgur.com/oauth2/addclient )

![image](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/124480833/73b748eb-a6d2-4845-bcbc-bd8ab92c6bde)

3. Click submit and grab the client id

<img width="815" alt="SCR-20230630-tgux" src="https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/124480833/638d400d-cd4e-4d73-8f36-0764d6b39375">

4. Input the ImgurClientID and ImgurRapidAPIKey in the Tweak.m file

5. Build the tweak, inject with sideloady (I used sideload spoofer option), signed with iosappsigner (though any flavor altstore, sidestore, should work here)

I used this version of the decrypted ipa (https://github.com/Barusu-rem/apollo-decrypt-legacy-version/releases/download/production/Apollo_1.15.11_decrypt.ipa) 

Steps above based on:
https://rapidapi.com/blog/imgur-api-tutorial/

Now the problem is after I install the modified app when trying to use the imgur uploader I get this error

![IMG_7D434F08709D-1](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/124480833/3d33b7d9-bb24-49fc-9ffe-b8487249d844)

Not sure where I made a mistake

**Comment by Barusu-rem** [comment]
> > I see that the code updated with Imgur support but how do I actually use it? I am registering an application in Imgur and it asked for callback. So what would I put? There’s also rapid api key that would require so much money to register 👀. Further advise needed.
> > thanks!
> 
> Spoiler I couldn't get it to work but this is what I tried.
> 
>     1. Sign up for X-rapid api key and copy key
> 
> 
> <img alt="SCR-20230630-thzf" width="1373" src="https://user-images.githubusercontent.com/124480833/250220960-28d774ad-083b-4dc5-b664-94cd11bd3c45.png"> 2. Create an imgur account and creat an app with the following parameters
> 
> https://api.imgur.com/oauth2/addclient
> 
> ![image](https://user-images.githubusercontent.com/124480833/250220998-73b748eb-a6d2-4845-bcbc-bd8ab92c6bde.png)
> 
>     3. Click submit and grab the client id
> 
> 
> <img alt="SCR-20230630-tgux" width="815" src="https://user-images.githubusercontent.com/124480833/250221081-638d400d-cd4e-4d73-8f36-0764d6b39375.png">
> 
>     4. Input the ImgurClientID and ImgurRapidAPIKey in the Tweak.m file
> 
>     5. Build the tweak, inject with sideloady (I used sideload spoofer option), signed with iosappsigner (though any flavor altstore, sidestore, should work here)
> 
> 
> I used this version of the decrypted ipa (https://github.com/Barusu-rem/apollo-decrypt-legacy-version/releases/download/production/Apollo_1.15.11_decrypt.ipa)
> 
> Steps above based on: https://rapidapi.com/blog/imgur-api-tutorial/
> 
> Now the problem is after I install the modified app when trying to use the imgur uploader I get this error
> 
> ![IMG_7D434F08709D-1](https://user-images.githubusercontent.com/124480833/250221337-3d33b7d9-bb24-49fc-9ffe-b8487249d844.jpeg)
> 
> Not sure where I made a mistake

Also seperate issue but viewing albums is also broken though that is a seperate issue relying on apollogur for caching (not sure what goes into that part of backend).

**Comment by madscientista** [comment]
@Barusu-rem Thanks for the detailed steps! Did you try this with 1.15.9? I am hesitant to update beyond that.

**Comment by Rihcus** [comment]
> @Barusu-rem Thanks for the detailed steps! Did you try this with 1.15.9? I am hesitant to update beyond that.

I tested with 1.15.11 though its not working for me.

@EthanArbuckle any ideas?

**Comment by madscientista** [comment]
I just tested this with 1.15.9 and same. Imgur does not seem to work.

**Comment by FlipABit** [comment]
Seems like you have to actually subscribe to RapidAPI which is a minimum of $500/month for Imgur access

**Comment by Barusu-rem** [comment]
> Seems like you have to actually subscribe to RapidAPI which is a minimum of $500/month for Imgur access

Unfortunatly you seem correct


Imgur:
![SCR-20230701-ibzf](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/124480833/4316c336-c237-405c-8986-f0365f5d24f0)

Reddit:
![SCR-20230701-icih](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/124480833/d3867c76-dc98-449c-b0bd-c7103c68a293)

**Comment by Barusu-rem** [comment]
> > Seems like you have to actually subscribe to RapidAPI which is a minimum of $500/month for Imgur access
> 
> Unfortunatly you seem correct
> 
> Imgur: ![SCR-20230701-ibzf](https://user-images.githubusercontent.com/124480833/250275128-4316c336-c237-405c-8986-f0365f5d24f0.png)
> 
> Reddit: ![SCR-20230701-icih](https://user-images.githubusercontent.com/124480833/250275162-d3867c76-dc98-449c-b0bd-c7103c68a293.png)

You would probably need to use imgurs free end poing
 https://api.imgur.com/3/image

**Comment by iCrazeiOS** [comment]
FWIW, my tweak "Artemis" has reimplemented imgur uploads and fetching

it's not perfect (imgur gifs are broken, and you can't upload multiple images at once), but should be good for most use cases

no need to enter an Imgur API key or anything, it'll just ask for your reddit client ID on startup and that's it

**Comment by Z3ROS1X** [comment]
> FWIW, my tweak "Artemis" has reimplemented imgur uploads and fetching
> 
> it's not perfect (imgur gifs are broken, and you can't upload multiple images at once), but should be good for most use cases
> 
> no need to enter an Imgur API key or anything, it'll just ask for your reddit client ID on startup and that's it

This is absolutely AMAZING, too! I’ve been using Artemis injected into Apollo v1.15.9 on iOS 16.1.2 for past couple hours or so and it’s so beautifully simplified. I love the initial popup to “authenticate” with your own personal Reddit API key and I especially love that I can upload to Imgur again now— wonderful work!!

However, I do have one question. After the initial popup to get Apollo configured to your your private API key there is nothing within the app indicating that a custom API has been used, i.e. a button or text somewhere stating this. Did you mean to leave text or a button out intentionally, or are you considering adding something in the future? Perhaps a button like what this tweak, ApolloPatcher, has done at the bottom of the Settings tab? That would be nifty, even though it isn’t necessary. 

“Sideload Spoofing” via Sideloadly gives a green popup banner at the launch of the app stating that the injected tweak is working properly. Either way, thank you for your phenomenal work so far! Keep it up! 😌👍

**Comment by madscientista** [comment]
@EthanArbuckle Any update on this?

**Comment by EthanArbuckle** [comment]
I've refactored the Imgur API stuff. The readme of this repo now contains instructions for adding Imgur creds

You'll just need the client_id from imgur.com. RapidShare is no longer used. 

Note: Imgur is removing all NSFW content from their platform. If you see posts that fail to load in Apollo's feed (even after adding your own Imgur credentials), it's due to Imgur gating their API

**Comment by madscientista** [comment]
@EthanArbuckle Sadly Imgur is still broken. Non-nsfw posts.

**Comment by zeldridge** [comment]
> @EthanArbuckle Sadly Imgur is still broken. Non-nsfw posts.

I too am finding that its not working with non-nsfw posts

**Comment by calania** [comment]
I also can't get it to work
